version: "3.7"
services:
  registry:
    image: registry:2
    restart: always
    container_name: myregistry
    ports:
     - "5000:5000"  
  postgresql:
    container_name: sonarqube-db
    build:
      context: postgres/
    networks:
      - sonarnet
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  sonarqube:
    container_name: sonarqube
    build:
      context: Tools/sonarqube/
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - sonarnet
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on: 
      - postgresql
  jenkins:
    container_name: jenkins
    build:
      context: jenkins/
    privileged: true
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    depends_on: 
      - sonarqube
networks:
  sonarnet:
    driver: bridge
volumes:
  jenkins_home:
  postgresql:
  postgresql_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
